import { Link } from 'react-router-dom'
import { useBooking } from '../BookingContext'
import { extras, packages, rooms } from '../data'
import { calculatePrice, formatCurrency, formatDate } from '../utils'

const countries: Record<string, string> = { DE: 'Germany', GB: 'United Kingdom', US: 'United States' }

export function BookingDetailsPage() {
  const { state } = useBooking()
  const room = rooms.find((item) => item.id === state.roomId)!
  const selectedPackage = packages.find((item) => item.id === state.packageId)!
  const selectedExtras = extras.filter((item) => (state.extras[item.id] ?? 0) > 0)
  const price = calculatePrice(state)

  return <section className="booking-details-page" data-test-id="booking-details-page">
    <div className="booking-details-heading" data-test-id="booking-details-heading-block"><p className="eyebrow" data-test-id="booking-details-eyebrow">Your reservation</p><h1 data-test-id="booking-details-heading">My Booking</h1><p data-test-id="booking-details-reference">Booking reference <strong data-test-id="booking-details-reference-value">{state.confirmation?.reference}</strong></p></div>
    <div className="booking-details-grid" data-test-id="booking-details-grid">
      <article className="details-section stay-details" data-test-id="booking-details-stay-section"><div className={`details-room-image ${room.imageClass}`} role="img" aria-label={room.name} data-test-id="booking-details-room-image"/><div data-test-id="booking-details-stay-copy"><p className="eyebrow" data-test-id="booking-details-stay-eyebrow">Stay details</p><h2 data-test-id="booking-details-room-name">{room.name}</h2><p data-test-id="booking-details-room-description">{room.description}</p><dl data-test-id="booking-details-stay-list"><div data-test-id="booking-details-checkin-row"><dt data-test-id="booking-details-checkin-label">Check in</dt><dd data-test-id="booking-details-checkin-value">{formatDate(state.search!.checkIn)}, from 15:00</dd></div><div data-test-id="booking-details-checkout-row"><dt data-test-id="booking-details-checkout-label">Check out</dt><dd data-test-id="booking-details-checkout-value">{formatDate(state.search!.checkOut)}, by 11:00</dd></div><div data-test-id="booking-details-duration-row"><dt data-test-id="booking-details-duration-label">Duration</dt><dd data-test-id="booking-details-duration-value">{price.nights} nights</dd></div><div data-test-id="booking-details-occupancy-row"><dt data-test-id="booking-details-occupancy-label">Guests</dt><dd data-test-id="booking-details-occupancy-value">{state.search?.adults} adults, {state.search?.children} children</dd></div></dl></div></article>
      <article className="details-section" data-test-id="booking-details-guest-section"><p className="eyebrow" data-test-id="booking-details-guest-eyebrow">Lead guest</p><h2 data-test-id="booking-details-guest-name">{state.guest?.title} {state.guest?.firstName} {state.guest?.lastName}</h2><dl data-test-id="booking-details-guest-list"><div data-test-id="booking-details-email-row"><dt data-test-id="booking-details-email-label">Email</dt><dd data-test-id="booking-details-email-value">{state.guest?.email}</dd></div><div data-test-id="booking-details-phone-row"><dt data-test-id="booking-details-phone-label">Phone</dt><dd data-test-id="booking-details-phone-value">{state.guest?.phone || 'Not provided'}</dd></div><div data-test-id="booking-details-country-row"><dt data-test-id="booking-details-country-label">Country</dt><dd data-test-id="booking-details-country-value">{countries[state.guest!.country] ?? state.guest?.country}</dd></div><div data-test-id="booking-details-arrival-row"><dt data-test-id="booking-details-arrival-label">Arrival</dt><dd data-test-id="booking-details-arrival-value">{state.guest?.arrivalTime}</dd></div><div data-test-id="booking-details-requests-row"><dt data-test-id="booking-details-requests-label">Requests</dt><dd data-test-id="booking-details-requests-value">{state.guest?.requests || 'None'}</dd></div></dl></article>
      <article className="details-section" data-test-id="booking-details-package-section"><p className="eyebrow" data-test-id="booking-details-package-eyebrow">Package & extras</p><h2 data-test-id="booking-details-package-name">{selectedPackage.name}</h2><p data-test-id="booking-details-package-description">{selectedPackage.description}</p><ul data-test-id="booking-details-package-features">{selectedPackage.features.map((feature) => <li key={feature} data-test-id={`booking-details-package-feature-${feature.toLowerCase().replaceAll(' ', '-')}`}>{feature}</li>)}</ul><h3 data-test-id="booking-details-extras-heading">Extras</h3>{selectedExtras.length ? <ul className="details-extras" data-test-id="booking-details-extras-list">{selectedExtras.map((extra) => <li key={extra.id} data-test-id={`booking-details-extra-${extra.id}`}><span data-test-id={`booking-details-extra-${extra.id}-name`}>{extra.name} × {state.extras[extra.id]}</span><strong data-test-id={`booking-details-extra-${extra.id}-price`}>{formatCurrency(extra.price * state.extras[extra.id])}</strong></li>)}</ul> : <p data-test-id="booking-details-no-extras">No extras selected</p>}</article>
      <article className="details-section" data-test-id="booking-details-payment-section"><p className="eyebrow" data-test-id="booking-details-payment-eyebrow">Payment summary</p><h2 data-test-id="booking-details-payment-heading">Paid in full</h2><dl data-test-id="booking-details-price-list"><div data-test-id="booking-details-room-price-row"><dt data-test-id="booking-details-room-price-label">Room</dt><dd data-test-id="booking-details-room-price-value">{formatCurrency(price.roomTotal)}</dd></div><div data-test-id="booking-details-package-price-row"><dt data-test-id="booking-details-package-price-label">Package</dt><dd data-test-id="booking-details-package-price-value">{formatCurrency(price.packageTotal)}</dd></div><div data-test-id="booking-details-extras-price-row"><dt data-test-id="booking-details-extras-price-label">Extras</dt><dd data-test-id="booking-details-extras-price-value">{formatCurrency(price.extrasTotal)}</dd></div><div data-test-id="booking-details-tax-row"><dt data-test-id="booking-details-tax-label">Taxes & fees</dt><dd data-test-id="booking-details-tax-value">{formatCurrency(price.taxes)}</dd></div><div className="total" data-test-id="booking-details-total-row"><dt data-test-id="booking-details-total-label">Total paid</dt><dd data-test-id="booking-details-total-value">{formatCurrency(price.total)}</dd></div></dl><p data-test-id="booking-details-card-summary">Paid with card ending {state.confirmation?.paymentLastFour}</p></article>
    </div>
    <div className="booking-details-actions" data-test-id="booking-details-actions"><Link to="/confirmation" className="secondary action-link" data-test-id="booking-details-back-link">Back to confirmation</Link><Link to="/" className="primary action-link" data-test-id="booking-details-home-link">Hotel home</Link></div>
  </section>
}
