import { Link, useNavigate } from 'react-router-dom'
import { useBooking } from '../BookingContext'
import { packages, rooms } from '../data'
import { calculatePrice, formatCurrency, formatDate } from '../utils'

export function ConfirmationPage() {
  const { state, dispatch } = useBooking(); const navigate = useNavigate(); const room = rooms.find(r=>r.id===state.roomId)!; const selectedPackage = packages.find(p=>p.id===state.packageId)!; const price = calculatePrice(state)
  const restart = () => { dispatch({type:'RESET'}); navigate('/') }
  return <section className="confirmation" data-test-id="confirmation-page"><div className="confirmation-icon" data-test-id="confirmation-success-icon" aria-hidden="true">✓</div><p className="eyebrow" data-test-id="confirmation-eyebrow">Reservation confirmed</p><h1 data-test-id="confirmation-heading">We’ll see you soon, {state.guest?.firstName}.</h1><p className="confirmation-lead" data-test-id="confirmation-lead">A confirmation has been sent to <strong data-test-id="confirmation-email">{state.guest?.email}</strong>.</p><div className="reference" data-test-id="confirmation-reference-panel"><span data-test-id="confirmation-reference-label">Booking reference</span><strong data-test-id="confirmation-reference-value">{state.confirmation?.reference}</strong></div><div className="confirmation-card" data-test-id="confirmation-details-card"><div className={`confirmation-image ${room.imageClass}`} data-test-id="confirmation-room-image" role="img" aria-label={room.name}/><div data-test-id="confirmation-details-copy"><h2 data-test-id="confirmation-room-name">{room.name}</h2><dl data-test-id="confirmation-details-list"><div data-test-id="confirmation-dates-row"><dt data-test-id="confirmation-dates-label">Dates</dt><dd data-test-id="confirmation-dates-value">{formatDate(state.search!.checkIn)} — {formatDate(state.search!.checkOut)}</dd></div><div data-test-id="confirmation-guests-row"><dt data-test-id="confirmation-guests-label">Guests</dt><dd data-test-id="confirmation-guests-value">{state.search?.adults} adults, {state.search?.children} children</dd></div><div data-test-id="confirmation-package-row"><dt data-test-id="confirmation-package-label">Package</dt><dd data-test-id="confirmation-package-value">{selectedPackage.name}</dd></div><div data-test-id="confirmation-payment-row"><dt data-test-id="confirmation-payment-label">Payment</dt><dd data-test-id="confirmation-payment-value">Card ending {state.confirmation?.paymentLastFour}</dd></div><div className="total" data-test-id="confirmation-total-row"><dt data-test-id="confirmation-total-label">Total paid</dt><dd data-test-id="confirmation-total-value">{formatCurrency(price.total)}</dd></div></dl></div></div><div className="confirmation-actions" data-test-id="confirmation-actions"><Link className="primary action-link" to="/my-booking" data-test-id="confirmation-my-booking-link">My Booking</Link><button className="secondary" onClick={restart} data-test-id="confirmation-new-booking-button">Make another booking</button></div></section>
}
