import { useNavigate } from 'react-router-dom'
import { useBooking } from '../BookingContext'
import { extras, packages } from '../data'
import { formatCurrency } from '../utils'
import { BookingSummary } from '../components/Summary'

export function PackagesPage() {
  const { state, dispatch } = useBooking(); const navigate = useNavigate()
  const quantity = (id: string) => state.extras[id] ?? 0
  const updateExtra = (id: string, value: number, max: number) => dispatch({ type: 'SET_EXTRA', payload: { id, quantity: Math.max(0, Math.min(max, value)) } })
  return <section className="content-page" data-test-id="packages-page"><div className="page-heading" data-test-id="packages-heading-block"><p className="eyebrow" data-test-id="packages-eyebrow">Make it yours</p><h1 data-test-id="packages-heading">Choose your experience</h1><p data-test-id="packages-subheading">Select one package, then add any finishing touches.</p></div>
    <div className="split-layout" data-test-id="packages-layout"><div data-test-id="packages-options-column"><fieldset className="package-list" data-test-id="packages-list"><legend data-test-id="packages-list-legend">Stay packages</legend>{packages.map(item => <label className={`package-card ${state.packageId === item.id ? 'selected' : ''}`} key={item.id} data-test-id={`packages-${item.id}-card`}><input type="radio" name="package" value={item.id} checked={state.packageId === item.id} onChange={() => dispatch({ type: 'SET_PACKAGE', payload: item.id })} data-test-id={`packages-${item.id}-radio`}/><span className="package-copy" data-test-id={`packages-${item.id}-copy`}><strong data-test-id={`packages-${item.id}-name`}>{item.name}</strong><small data-test-id={`packages-${item.id}-description`}>{item.description}</small><span data-test-id={`packages-${item.id}-features`}>{item.features.join(' · ')}</span></span><b data-test-id={`packages-${item.id}-price`}>{item.pricePerNight ? `+ ${formatCurrency(item.pricePerNight)} / night` : 'Included'}</b></label>)}</fieldset>
      <fieldset className="extras-list" data-test-id="packages-extras-list"><legend data-test-id="packages-extras-legend">Optional extras</legend>{extras.map(extra => <div className="extra-card" key={extra.id} data-test-id={`packages-extra-${extra.id}-card`}><label data-test-id={`packages-extra-${extra.id}-label`}><input type="checkbox" checked={quantity(extra.id)>0} onChange={e => updateExtra(extra.id, e.target.checked ? 1 : 0, extra.maxQuantity)} data-test-id={`packages-extra-${extra.id}-checkbox`}/><span data-test-id={`packages-extra-${extra.id}-copy`}><strong data-test-id={`packages-extra-${extra.id}-name`}>{extra.name}</strong><small data-test-id={`packages-extra-${extra.id}-description`}>{extra.description}</small></span></label><span data-test-id={`packages-extra-${extra.id}-price`}>{formatCurrency(extra.price)} {extra.unit}</span>{quantity(extra.id)>0 && <div className="quantity" data-test-id={`packages-extra-${extra.id}-quantity`}><button type="button" onClick={() => updateExtra(extra.id, quantity(extra.id)-1, extra.maxQuantity)} data-test-id={`packages-extra-${extra.id}-decrease`} aria-label={`Decrease ${extra.name}`}>−</button><output data-test-id={`packages-extra-${extra.id}-count`}>{quantity(extra.id)}</output><button type="button" onClick={() => updateExtra(extra.id, quantity(extra.id)+1, extra.maxQuantity)} data-test-id={`packages-extra-${extra.id}-increase`} aria-label={`Increase ${extra.name}`}>+</button></div>}</div>)}</fieldset>
      <button className="primary wide" disabled={!state.packageId} onClick={() => navigate(state.flowVariant === 'standard' ? '/guest-information' : '/checkout')} data-test-id="packages-continue-button">{state.uiVersion === 'v2' ? (state.flowVariant === 'standard' ? 'Next: your details' : 'Next: checkout') : (state.flowVariant === 'standard' ? 'Continue to guest information' : 'Continue to checkout')} <span data-test-id="packages-continue-arrow">→</span></button></div><BookingSummary testId="packages-summary" /></div>
  </section>
}
